# Hyperparameter Tuning

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = sns.load_dataset("iris")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

:

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

:

In [ ]:
from sklearn.model_selection import train_test_split

:

In [ ]:
x = df.drop('species' , axis = 1)
y = df['species']

:

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=42)

:

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=9)

:

In [ ]:
model_knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=9)

:

In [ ]:
model_knn.score(x_test,y_test)

1.0

:

# SVM

In [ ]:
from sklearn.svm import SVC

model_SVM = SVC(C=30 , kernel='rbf' , gamma='auto')

:

In [ ]:
model_SVM.fit(x_train , y_train)

SVC(C=30, gamma='auto')

:

In [ ]:
model_SVM.score(x_test,y_test)

1.0

:

# Grid Search CV

In [ ]:
from sklearn.model_selection import GridSearchCV

:

In [ ]:
classifier = GridSearchCV((model_SVM ), {
    'C' : [1,10,20,30],
    'kernel' : ['rbf', 'linear'],
} , cv=5 , return_train_score=False)

:

In [ ]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

:

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.04002066, 0.01475487, 0.02362347, 0.00516248, 0.0049499 ,
        0.00412951, 0.00501261, 0.00407858]),
 'std_fit_time': array([0.02950639, 0.00946661, 0.01201107, 0.00171879, 0.00181435,
        0.0013733 , 0.00296401, 0.00093438]),
 'mean_score_time': array([0.04153714, 0.01153717, 0.03095188, 0.00433288, 0.00367355,
        0.00282273, 0.00359187, 0.00291018]),
 'std_score_time': array([0.02948331, 0.00317637, 0.03572033, 0.00267243, 0.00110452,
        0.00075181, 0.00185932, 0.00114351]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7])}

:

In [ ]:
result = pd.DataFrame(classifier.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.040021,0.029506,0.041537,0.029483,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.014755,0.009467,0.011537,0.003176,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.023623,0.012011,0.030952,0.035720,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.005162,0.001719,0.004333,0.002672,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.004950,0.001814,0.003674,0.001105,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.004130,0.001373,0.002823,0.000752,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.005013,0.002964,0.003592,0.001859,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.004079,0.000934,0.002910,0.001144,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

:

In [ ]:
result[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

:

# Random Search CV

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

:

In [ ]:
classifier_random = RandomizedSearchCV((model_SVM ), {
    'C' : [1,10,20,30],
    'kernel' : ['rbf', 'linear'],
} ,n_iter = 4, cv = 5 , return_train_score=False)

:

In [ ]:
classifier_random.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

:

In [ ]:
result = pd.DataFrame(classifier_random.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004802,0.001814,0.003071,0.001073,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004484,0.000883,0.005253,0.003280,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
2,0.006438,0.001682,0.004448,0.001885,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
3,0.009835,0.009268,0.004714,0.001730,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4

:

In [ ]:
result[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       20          rbf         0.966667
2       10       linear         0.973333
3       30       linear         0.960000

: